version: "3.2"

services:

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  server:
    image: jeongyeonjun/tovalley-server
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: always
    environment:
      RDS_HOSTNAME: ${RDS_HOSTNAME}
      RDS_PORT: ${RDS_PORT}
      RDS_DB_NAME: ${RDS_DB_NAME}
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
      KEY_OPENWEATHER: ${KEY_OPENWEATHER}
      KEY_SPECIALWEATHER: ${KEY_SPECIALWEATHER}
      KEY_GOOGLEMAP: ${KEY_GOOGLEMAP}
      KEY_GEOCODING: ${KEY_GEOCODING}
      KEY_WATERPLACE: ${KEY_WATERPLACE}
      KAKAO_CLIENTID: ${KAKAO_CLIENTID}
      KAKAO_CLIENTSECRET: ${KAKAO_CLIENTSECRET}
      KAKAO_REDIRECTURL: ${KAKAO_REDIRECTURL}
      GOOGLE_CLIENTID: ${GOOGLE_CLIENTID}
      GOOGLE_CLIENTSECRET: ${GOOGLE_CLIENTSECRET}
      GOOGLE_REDIRECTURL: ${GOOGLE_REDIRECTURL}
      NAVER_CLIENTID: ${NAVER_CLIENTID}
      NAVER_CLIENTSECRET: ${NAVER_CLIENTSECRET}
      NAVER_REDIRECTURL: ${NAVER_REDIRECTURL}
      JWT_SUBJECT: ${JWT_SUBJECT}
      JWT_SECRET: ${JWT_SECRET}
      CLOUD_AWS_CREDENTIALS_ACCESSKEY: ${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
      CLOUD_AWS_CREDENTIALS_SECRETKEY: ${CLOUD_AWS_CREDENTIALS_SECRETKEY}
      CLOUD_AWS_S3_BUCKET: ${CLOUD_AWS_S3_BUCKET}
      CLOUD_AWS_REGION_STATIC: ${CLOUD_AWS_REGION_STATIC}
      CLOUD_AWS_STACK_AUTO: ${CLOUD_AWS_STACK_AUTO}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_NICKNAME: ${ADMIN_NICKNAME}
    networks:
      - mynetwork

  react:
    image: jeongyeonjun/tovalley-react
    ports:
      - 80:80
    depends_on:
      - server
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge