 spring:
  profiles:
    active:
      - dev
    include: secret-key
  sql:
    init:
      mode: always # 서버 시작시 항상 classpath의 sql문을 실행하도록 설정
      continue-on-error: true # 서버 시작시 sql문을 실행할 때 오류 무시하고 계속 진행
      schema-locations: classpath:db/schema.sql # 서버 시작시 ddl sql문을 실행할 위치 및 파일 지정
      data-locations: classpath:db/data.sql # 서버 시작시 dml sql문을 실행할 위치 및 파일 지정