 spring:
  profiles:
    active:
      - dev
    include: secret-key
  sql:
    init:
      mode: always # 서버 시작시 항상 classpath의 sql문을 실행하도록 설정
      continue-on-error: true # 서버 시작시 sql문을 실행할 때 오류 무시하고 계속 진행
      schema-locations: classpath:db/schema.sql # 서버 시작시 ddl sql문을 실행할 위치 및 파일 지정
      data-locations: classpath:db/data.sql # 서버 시작시 dml sql문을 실행할 위치 및 파일 지정

 springdoc:
   packages-to-scan: kr.ac.kumoh.illdang100.tovalley
   default-consumes-media-type: application/json;charset=UTF-8
   default-produces-media-type: application/json;charset=UTF-8
   swagger-ui:
     path: swagger-ui.html            # Swagger UI 경로 => localhost:8000/swagger-ui.html
     tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
     operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
   api-docs:
     path: /api-docs/json
     groups:
       enabled: true
   cache:
     disabled: true
     
 logging:
   level:
     com:
       amazonaws:
         util:
           EC2MetadataUtils: error