name: Build and Deploy

on:
  push:
    branches:
      - deploy/docker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: make application.properties
        working-directory: ./tovalley-server
        run: |
          # cd ./src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.PROPERTIES }}" > ./application-prod.yml

      ### CI
      #gradlew 권한 추가
      - name: Grant Execute Permission For Gradlew
        working-directory: ./tovalley-server
        run: chmod +x gradlew

      #test를 제외한 프로젝트 빌드
      - name: Build With Gradle
        working-directory: ./tovalley-server
        run: ./gradlew build -x test

      - name: Setup Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Environment Variables
        run: |
          echo "${{ secrets.PROJECT_ENVIRONMENT }}" > .env
          export $(cat .env | xargs)

      - name: Build and Push tovalley-react Docker Image
        working-directory: ./tovalley-react
        run: |
          docker build -t jeongyeonjun/tovalley-react:latest .
          docker push jeongyeonjun/tovalley-react:latest

      - name: Build and Push tovalley-server Docker Image
        working-directory: ./tovalley-server
        run: |
          docker build -t jeongyeonjun/tovalley-server:latest .
          docker push jeongyeonjun/tovalley-server:latest

      # UTC가 기준이기 때문에 한국시간으로 맞추려면 +9시간 해야 한다.
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
        shell: bash

      - name: SSH into EC2 and Stop Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "------------ 프로젝트 종료 중 ------------"
            docker stop $(docker ps -q)
            docker rm $(docker ps -a -q)
            docker rmi -f $(docker images -q)
            cd ~/tovalley
            rm docker-compose.yml
            echo "------------ 프로젝트 종료 완료 ------------"

      - name: copy docker-compose.yml via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/tovalley"

      - name: SSH into EC2 and Start Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "------------ 프로젝트 재실행 ------------"
            cd ~/tovalley
            docker-compose up -d
            echo "------------ 프로젝트 재실행 완료 ------------"
