name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[deploy]')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # UTC가 기준이기 때문에 한국시간으로 맞추려면 +9시간 해야 한다.
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
        shell: bash

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Set up Redis server
        uses: supercharge/redis-github-action@1.2.0

      - name: Make application-prod.yml
        working-directory: ./tovalley-server
        run: |
          touch ./application-prod.yml
          echo "${{ secrets.PROPERTIES }}" > ./application-prod.yml

      - name: Make React .env
        working-directory: ./tovalley-react
        run: |
          touch ./.env
          echo "${{ secrets.REACT_ENV }}" > ./.env

      - name: Grant Execute Permission For Gradlew
        working-directory: ./tovalley-server
        run: chmod +x gradlew

      - name: Make application-test.yml
        working-directory: ./tovalley-server
        run: |
          touch ./application-test.yml
          echo "${{ secrets.TEST_PROPERTIES }}" > ./application-test.yml

      - name: Build With Gradle
        working-directory: ./tovalley-server
        run: ./gradlew build

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push tovalley-react Docker Image
        working-directory: ./tovalley-react
        run: |
          docker build -t jeongyeonjun/tovalley-react:latest .
          docker push jeongyeonjun/tovalley-react:latest

      - name: Build and Push tovalley-server Docker Image
        working-directory: ./tovalley-server
        run: |
          docker build -t jeongyeonjun/tovalley-server:latest .
          docker push jeongyeonjun/tovalley-server:latest

      - name: SSH into EC2 and Stop Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "------------ 프로젝트 종료 중 ------------"
            docker stop $(docker ps -q)
            docker rm $(docker ps -a -q)
            docker rmi -f $(docker images -q)
            cd ~/tovalley
            rm docker-compose.yml
            echo "------------ 프로젝트 종료 완료 ------------"

      - name: copy docker-compose.yml via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/tovalley"

      - name: SSH into EC2 and Start Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "------------ 프로젝트 재실행 ------------"
            cd ~/tovalley
            docker-compose up -d
            echo "------------ 프로젝트 재실행 완료 ------------"
