name: Build and Deploy

on:
  push:
    branches:
      - deploy/docker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push tovalley-react Docker Image
        working-directory: ./tovalley-react
        run: |
          docker build -t jeongyeonjun/tovalley-react:latest .
          docker push jeongyeonjun/tovalley-react:latest

      - name: Build and Push tovalley-server Docker Image
        working-directory: ./tovalley-server
        run: |
          docker build -t jeongyeonjun/tovalley-server:latest .
          docker push jeongyeonjun/tovalley-server:latest

      - name: SSH into EC2 and Stop Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "------------ 프로젝트 종료 중 ------------"
            docker stop $(docker ps -q)
            docker rm $(docker ps -a -q)
            docker rmi -f $(docker images -q)
            cd ~/tovalley
            rm docker-compose.yml
            echo "------------ 프로젝트 종료 완료 ------------"

      - name: copy docker-compose.yml via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/tovalley"

      - name: SSH into EC2 and Start Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "------------ 프로젝트 재실행 ------------"
            cd ~/tovalley
            docker-compose up -d
            echo "------------ 프로젝트 재실행 완료 ------------"
