# name: Deploy to AWS EC2

# on:
#   push:
#     branches:
#       - deploy/docker

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       # - name: Set up Docker
#       #   run: |
#       #     sudo apt-get update
#       #     sudo apt-get install -y docker.io
#       #     sudo systemctl start docker
#       #     sudo systemctl enable docker

#       # - name: Install Docker Compose
#       #   run: |
#       #     sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
#       #     sudo chmod +x /usr/local/bin/docker-compose

#       - name: Log in to Docker Hub
#         run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and Push Docker images
#         run: |
#           docker-compose -f docker-compose.yml build
#           docker-compose -f docker-compose.yml push

#       - name: SSH into EC2 and Deploy
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USERNAME }}
#           key: ${{ secrets.EC2_PRIVATE_KEY }}
#           # port: ${{ secrets.EC2_PORT }}
#           script: |
#             docker-compose -f /home/ubuntu/tovalley/docker-compose.yml up -d

name: Build and Deploy

on:
  push:
    branches:
      - deploy/docker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push tovalley-react Docker Image
        working-directory: ./tovalley-react
        run: |
          docker build -t jeongyeonjun/tovalley-react:latest .
          docker push jeongyeonjun/tovalley-react:latest

      - name: Build and Push tovalley-server Docker Image
        working-directory: ./tovalley-server
        run: |
          docker build -t jeongyeonjun/tovalley-server:latest .
          docker push jeongyeonjun/tovalley-server:latest

      - name: Copy docker-compose.yml to EC2
        run: scp -i ${{ secrets.EC2_PRIVATE_KEY }} docker-compose.yml ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/tovalley

      - name: SSH into EC2 and Start Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd ~/tovalley && docker-compose up -d"
