name: Deploy to AWS EC2

on:
  push:
    branches:
      - deploy/docker

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        - name: Update and Upgrade Packages
          run: |
            sudo apt-get update
            sudo apt-get upgrade -y

        - name: Install required packages
          run: |
            sudo apt-get install -y containerd

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Build and Push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          # port: ${{ secrets.EC2_PORT }}
          script: |
            docker-compose -f docker-compose.yml up -d
